package opml

import (
	"bytes"
	"testing"
)

func TestOPML(t *testing.T) {

	document := `
	<?xml version="1.0" encoding="UTF-8"?>
	<opml version="1.0">
	<!-- OPML generated by Fever -->
	<head><title>Fever</title></head>
	<body>
	<outline text="GroupA">
		<outline type="rss" text="2ality" title="2ality" xmlUrl="https://feeds.feedburner.com/2ality?format=xml" htmlUrl="http://www.2ality.com/"/>
		<outline type="rss" text="37 Signals" title="37 Signals" xmlUrl="https://feeds.feedburner.com/37signals/beMH" htmlUrl="http://37signals.com/svn/posts"/>
		<outline type="rss" text="Andyet" title="Andyet" xmlUrl="https://blog.andyet.com/feeds/all.atom.xml" htmlUrl="http://blog.andyet.com"/>
		<outline type="rss" text="AngularJS" title="AngularJS" xmlUrl="https://blog.angularjs.org/feeds/posts/default" htmlUrl="http://blog.angularjs.org/"/>
	</outline>
	<outline text="GroupB">
		<outline type="rss" text="2ality" title="2ality" xmlUrl="https://feeds.feedburner.com/2ality?format=xml" htmlUrl="http://www.2ality.com/"/>
		<outline type="rss" text="37 Signals" title="37 Signals" xmlUrl="https://feeds.feedburner.com/37signals/beMH" htmlUrl="http://37signals.com/svn/posts"/>
		<outline type="rss" text="Andyet" title="Andyet" xmlUrl="https://blog.andyet.com/feeds/all.atom.xml" htmlUrl="http://blog.andyet.com"/>
		<outline type="rss" text="AngularJS" title="AngularJS" xmlUrl="https://blog.angularjs.org/feeds/posts/default" htmlUrl="http://blog.angularjs.org/"/>
		<outline text="GroupC" category="autoread">
			<outline type="rss" text="2ality" title="2ality" xmlUrl="https://feeds.feedburner.com/2ality?format=xml" htmlUrl="http://www.2ality.com/"/>
			<outline type="rss" text="37 Signals" title="37 Signals" xmlUrl="https://feeds.feedburner.com/37signals/beMH" htmlUrl="http://37signals.com/svn/posts"/>
			<outline type="rss" text="Andyet" title="Andyet" xmlUrl="https://blog.andyet.com/feeds/all.atom.xml" htmlUrl="http://blog.andyet.com"/>
			<outline type="rss" text="AngularJS" title="AngularJS" xmlUrl="https://blog.angularjs.org/feeds/posts/default" htmlUrl="http://blog.angularjs.org/"/>
		</outline>
	</outline>
	</body>
	</opml>`

	opml, err := Parse(bytes.NewReader([]byte(document)))
	if err != nil {
		t.Fatalf("Cannot parse opml document: %s", err.Error())
	}
	if opml == nil {
		t.Fatal("Invalid opml document")
	}

	result := Flatten(opml.Body)
	if len(result) != 3 {
		t.Errorf("bad number of groups: expected %d, actual %d", 3, len(result))
	}

	for k, v := range result {
		for _, outline := range v {
			t.Logf("%s - %t %t %s", k.Name, k.AutoRead, k.AutoStar, outline.Title)
		}
	}

}
