// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	PingRequest
	PingResponse
	StatusRequest
	StatusResponse
	TokenRequest
	TokenResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingResponse struct {
	Time int64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StatusResponse struct {
	Version   string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	BuildTime int64  `protobuf:"varint,2,opt,name=buildTime" json:"buildTime,omitempty"`
	BuildHash string `protobuf:"bytes,3,opt,name=buildHash" json:"buildHash,omitempty"`
	AppStart  int64  `protobuf:"varint,4,opt,name=appStart" json:"appStart,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type TokenRequest struct {
}

func (m *TokenRequest) Reset()                    { *m = TokenRequest{} }
func (m *TokenRequest) String() string            { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()               {}
func (*TokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type TokenResponse struct {
	Token      string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Expiration int64  `protobuf:"varint,2,opt,name=expiration" json:"expiration,omitempty"`
}

func (m *TokenResponse) Reset()                    { *m = TokenResponse{} }
func (m *TokenResponse) String() string            { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()               {}
func (*TokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*PingRequest)(nil), "pb.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "pb.PingResponse")
	proto.RegisterType((*StatusRequest)(nil), "pb.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "pb.StatusResponse")
	proto.RegisterType((*TokenRequest)(nil), "pb.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "pb.TokenResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for PingService service

type PingServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (PingService_PingClient, error)
}

type pingServiceClient struct {
	cc *grpc.ClientConn
}

func NewPingServiceClient(cc *grpc.ClientConn) PingServiceClient {
	return &pingServiceClient{cc}
}

func (c *pingServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (PingService_PingClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PingService_serviceDesc.Streams[0], c.cc, "/pb.PingService/Ping", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingServicePingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PingService_PingClient interface {
	Recv() (*PingResponse, error)
	grpc.ClientStream
}

type pingServicePingClient struct {
	grpc.ClientStream
}

func (x *pingServicePingClient) Recv() (*PingResponse, error) {
	m := new(PingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PingService service

type PingServiceServer interface {
	Ping(*PingRequest, PingService_PingServer) error
}

func RegisterPingServiceServer(s *grpc.Server, srv PingServiceServer) {
	s.RegisterService(&_PingService_serviceDesc, srv)
}

func _PingService_Ping_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingServiceServer).Ping(m, &pingServicePingServer{stream})
}

type PingService_PingServer interface {
	Send(*PingResponse) error
	grpc.ServerStream
}

type pingServicePingServer struct {
	grpc.ServerStream
}

func (x *pingServicePingServer) Send(m *PingResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PingService",
	HandlerType: (*PingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ping",
			Handler:       _PingService_Ping_Handler,
			ServerStreams: true,
		},
	},
}

// Client API for StatusService service

type StatusServiceClient interface {
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type statusServiceClient struct {
	cc *grpc.ClientConn
}

func NewStatusServiceClient(cc *grpc.ClientConn) StatusServiceClient {
	return &statusServiceClient{cc}
}

func (c *statusServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/pb.StatusService/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StatusService service

type StatusServiceServer interface {
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
}

func RegisterStatusServiceServer(s *grpc.Server, srv StatusServiceServer) {
	s.RegisterService(&_StatusService_serviceDesc, srv)
}

func _StatusService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StatusService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatusService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StatusService",
	HandlerType: (*StatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _StatusService_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

// Client API for TokenService service

type TokenServiceClient interface {
	GetToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
}

type tokenServiceClient struct {
	cc *grpc.ClientConn
}

func NewTokenServiceClient(cc *grpc.ClientConn) TokenServiceClient {
	return &tokenServiceClient{cc}
}

func (c *tokenServiceClient) GetToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := grpc.Invoke(ctx, "/pb.TokenService/GetToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TokenService service

type TokenServiceServer interface {
	GetToken(context.Context, *TokenRequest) (*TokenResponse, error)
}

func RegisterTokenServiceServer(s *grpc.Server, srv TokenServiceServer) {
	s.RegisterService(&_TokenService_serviceDesc, srv)
}

func _TokenService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TokenService/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).GetToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TokenService",
	HandlerType: (*TokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _TokenService_GetToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x92, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x95, 0xb6, 0x40, 0x73, 0x7a, 0xb7, 0x0a, 0x8a, 0xa2, 0x0a, 0x21, 0x4f, 0x88, 0xa1,
	0x45, 0x65, 0x63, 0x63, 0xe0, 0x22, 0xa6, 0xaa, 0xad, 0x58, 0x98, 0x12, 0xb0, 0x8a, 0x45, 0x89,
	0x4d, 0xec, 0x56, 0xcc, 0x7d, 0x05, 0x1e, 0x8d, 0x57, 0xe0, 0x41, 0x70, 0x8e, 0xed, 0x26, 0x6c,
	0xf9, 0x3f, 0xfb, 0x7c, 0x3e, 0xfa, 0x15, 0x08, 0x13, 0xc9, 0xc7, 0x32, 0x17, 0x5a, 0x90, 0x9a,
	0x4c, 0xe3, 0xd1, 0x4a, 0x88, 0xd5, 0x9a, 0x4d, 0x0c, 0x9d, 0x24, 0x59, 0x26, 0x74, 0xa2, 0xb9,
	0xc8, 0x94, 0xbd, 0x41, 0x3b, 0xd0, 0x9a, 0xf1, 0x6c, 0x35, 0x67, 0x9f, 0x1b, 0xa6, 0x34, 0xa5,
	0xd0, 0xb6, 0x51, 0x49, 0x73, 0x87, 0x11, 0x02, 0x0d, 0xcd, 0x3f, 0x58, 0x14, 0x9c, 0x05, 0xe7,
	0xf5, 0x39, 0x7e, 0xd3, 0x1e, 0x74, 0x16, 0x46, 0xb2, 0x51, 0x7e, 0x68, 0x17, 0x40, 0xd7, 0x13,
	0x37, 0x17, 0xc1, 0xd1, 0x96, 0xe5, 0xca, 0x3c, 0x84, 0xa3, 0xe1, 0xdc, 0x47, 0x32, 0x82, 0x30,
	0xdd, 0xf0, 0xf5, 0xeb, 0xb2, 0xd0, 0xd6, 0x50, 0x5b, 0x82, 0xfd, 0xe9, 0x43, 0xa2, 0xde, 0xa2,
	0x3a, 0x4e, 0x96, 0x80, 0xc4, 0xd0, 0x4c, 0xa4, 0x34, 0x4f, 0xe5, 0x3a, 0x6a, 0xe0, 0xe8, 0x3e,
	0xd3, 0x2e, 0xb4, 0x97, 0xe2, 0x9d, 0x65, 0x7e, 0xa9, 0x5b, 0xe8, 0xb8, 0xec, 0x56, 0x1a, 0xc2,
	0x81, 0x2e, 0x80, 0x5b, 0xc8, 0x06, 0x72, 0x0a, 0xc0, 0xbe, 0x24, 0xcf, 0xb1, 0x14, 0xb7, 0x4f,
	0x85, 0x4c, 0x67, 0xb6, 0x9f, 0x05, 0xcb, 0xb7, 0xfc, 0x85, 0x91, 0x1b, 0x68, 0x14, 0x91, 0xf4,
	0xc6, 0x32, 0x1d, 0x57, 0x8a, 0x8b, 0xfb, 0x25, 0xb0, 0xef, 0xd1, 0xe1, 0xee, 0xe7, 0xf7, 0xbb,
	0xd6, 0xa5, 0x21, 0x36, 0x2f, 0xcd, 0xd1, 0x75, 0x70, 0x71, 0x19, 0x4c, 0x9f, 0x7d, 0x7d, 0xde,
	0xf9, 0x08, 0xe1, 0x3d, 0xd3, 0x96, 0x91, 0x41, 0xe1, 0xf9, 0x57, 0x6f, 0x4c, 0xaa, 0xc8, 0xc9,
	0x4f, 0x50, 0xde, 0xa7, 0x2d, 0x94, 0x2b, 0x3c, 0x34, 0xfa, 0xe9, 0x93, 0x6b, 0xc1, 0xbb, 0xef,
	0xa0, 0x69, 0xdc, 0x88, 0x08, 0xae, 0x58, 0xed, 0x28, 0x1e, 0x54, 0x88, 0x13, 0x1f, 0xa3, 0xb8,
	0x47, 0x01, 0xc5, 0xd8, 0x91, 0xf1, 0xa6, 0x87, 0xf8, 0xb7, 0x5c, 0xfd, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x6f, 0x54, 0x38, 0x3a, 0x5c, 0x02, 0x00, 0x00,
}
